# NeON Build File (http://github.com/c4s4/neon)

default: [clean, format, test, run]
extends:
- c4s4/build/python.yml
- c4s4/build/release.yml

targets:

  run:
    doc: Run on all examples
    steps:
    - mkdir: =BUILD_DIR
    - $: ['={VENV_DIR}/bin/python', 'ride', 'examples', =BUILD_DIR]
